export type GradeScaleEntry = { letter: string; gpa: number; minPercentage: number; maxPercentage: number };
export type GradeRow = { id: string; name: string; grade: string; weight: string };
export const standardGradeScale: GradeScaleEntry[] = [
  { letter: "A+", gpa: 4.3, minPercentage: 97, maxPercentage: 100 }, { letter: "A", gpa: 4, minPercentage: 93, maxPercentage: 96.99 }, { letter: "A-", gpa: 3.7, minPercentage: 90, maxPercentage: 92.99 }, { letter: "B+", gpa: 3.3, minPercentage: 87, maxPercentage: 89.99 }, { letter: "B", gpa: 3, minPercentage: 83, maxPercentage: 86.99 }, { letter: "B-", gpa: 2.7, minPercentage: 80, maxPercentage: 82.99 }, { letter: "C+", gpa: 2.3, minPercentage: 77, maxPercentage: 79.99 }, { letter: "C", gpa: 2, minPercentage: 73, maxPercentage: 76.99 }, { letter: "C-", gpa: 1.7, minPercentage: 70, maxPercentage: 72.99 }, { letter: "D+", gpa: 1.3, minPercentage: 67, maxPercentage: 69.99 }, { letter: "D", gpa: 1, minPercentage: 63, maxPercentage: 66.99 }, { letter: "D-", gpa: .7, minPercentage: 60, maxPercentage: 62.99 }, { letter: "F", gpa: 0, minPercentage: 0, maxPercentage: 59.99 },
];
export const percentageToLetter = (percentage: number, scale = standardGradeScale) => scale.find((entry) => percentage >= entry.minPercentage && percentage <= entry.maxPercentage)?.letter;
export const letterToPercentage = (letter: string, scale = standardGradeScale) => { const entry = scale.find((item) => item.letter === letter.trim().toUpperCase()); return entry ? (entry.minPercentage + entry.maxPercentage) / 2 : undefined; };
export const letterToGPA = (letter: string, scale = standardGradeScale) => scale.find((item) => item.letter === letter.trim().toUpperCase())?.gpa;
export const parseGrade = (grade: string, scale = standardGradeScale): { value: number } | { error: string } => { const normalized = grade.trim(); if (!normalized) return { error: "Enter a grade." }; const numeric = Number(normalized); if (Number.isFinite(numeric)) return numeric >= 0 && numeric <= 100 ? { value: numeric } : { error: "Enter a grade between 0 and 100." }; const value = letterToPercentage(normalized, scale); return value === undefined ? { error: "Enter a valid letter grade such as A, B+, or C-." } : { value }; };
export type WeightedGradeResult = { average?: number; contribution: number; completedWeight: number; errors: Record<string, string>; rows: { id: string; grade: number; weight: number; contribution: number }[] };
export function calculateWeightedGrade(rows: GradeRow[], scale = standardGradeScale): WeightedGradeResult { const errors: Record<string, string> = {}; const valid = rows.flatMap((row) => { const grade = parseGrade(row.grade, scale), weight = Number(row.weight); if (!row.name.trim()) errors[`${row.id}-name`] = "Enter an assignment name."; if ("error" in grade) errors[`${row.id}-grade`] = grade.error; if (!Number.isFinite(weight) || weight < 0 || weight > 100) errors[`${row.id}-weight`] = "Enter a weight from 0 to 100%."; return "value" in grade && Number.isFinite(weight) && weight >= 0 && weight <= 100 ? [{ id: row.id, grade: grade.value, weight, contribution: grade.value * weight / 100 }] : []; }); const completedWeight = valid.reduce((sum, row) => sum + row.weight, 0); if (completedWeight > 100) errors.totalWeight = "Total completed weight cannot exceed 100%."; const contribution = valid.reduce((sum, row) => sum + row.contribution, 0); return { average: completedWeight && !errors.totalWeight ? contribution / (completedWeight / 100) : undefined, contribution, completedWeight, errors, rows: valid }; }
export function calculateRequiredRemainingGrade(target: number, currentContribution: number, remainingWeight: number) { if (!Number.isFinite(target) || target < 0 || target > 100) return { error: "Enter a target grade between 0 and 100." }; if (!Number.isFinite(remainingWeight) || remainingWeight <= 0 || remainingWeight > 100) return { error: "Enter a remaining weight greater than 0 and no more than 100%." }; const required = (target - currentContribution) / (remainingWeight / 100); return { required, status: required > 100 ? "impossible" as const : required <= 0 ? "secured" as const : "needed" as const }; }
export const calculateRequiredFinalGrade = (current: number, target: number, finalWeight: number) => calculateRequiredRemainingGrade(target, current * (1 - finalWeight / 100), finalWeight);
