"use client";
import { useMemo, useState } from "react";
import type { Calculator } from "@/lib/calculators";
import { defaultAIModel } from "@/lib/ai-pricing";
const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);
const decimal = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);
type Result = { primary: string; label: string; rows: [string, string][] };
function calculate(c: Calculator, v: Record<string, number>): Result {
  const f = (x: number) => Number.isFinite(x) ? decimal(x) : "—"; const usd = (x: number) => Number.isFinite(x) ? currency(x) : "—";
  switch(c.formula) {
    case "salaryHourly": return {primary: usd(v.salary/(v.hours*v.weeks)),label:"Estimated hourly rate",rows:[["Weekly",usd(v.salary/v.weeks)],["Monthly",usd(v.salary/12)],["Annual",usd(v.salary)]]};
    case "hourlySalary": { const annual=v.rate*v.hours*v.weeks; return {primary:usd(annual),label:"Estimated annual pay",rows:[["Weekly",usd(v.rate*v.hours)],["Monthly",usd(annual/12)],["Hourly",usd(v.rate)]]}; }
    case "overtime": return {primary:usd(v.rate*v.hours*v.multiplier),label:"Overtime pay",rows:[["Base rate",usd(v.rate)],["Overtime rate",usd(v.rate*v.multiplier)]]};
    case "tip": {const tip=v.bill*v.tip/100,total=v.bill+tip;return {primary:usd(total/v.people),label:"Total per person",rows:[["Tip",usd(tip)],["Bill total",usd(total)]]};}
    case "discount": {const saved=v.price*v.discount/100;return {primary:usd(v.price-saved),label:"Sale price",rows:[["You save",usd(saved)],["Original price",usd(v.price)]]};}
    case "margin": {const p=v.revenue-v.cost;return {primary:f(p/v.revenue*100)+"%",label:"Profit margin",rows:[["Profit",usd(p)],["Revenue",usd(v.revenue)]]};}
    case "markup": {const sale=v.cost*(1+v.markup/100);return {primary:usd(sale),label:"Selling price",rows:[["Markup amount",usd(sale-v.cost)],["Cost",usd(v.cost)]]};}
    case "commission": return {primary:usd(v.sales*v.rate/100),label:"Estimated commission",rows:[["Sales",usd(v.sales)],["Rate",f(v.rate)+"%"]]};
    case "loan": {const r=v.rate/100/12, months=v.years*12, payment=v.principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);return {primary:usd(payment),label:"Estimated monthly payment",rows:[["Total paid",usd(payment*months)],["Interest",usd(payment*months-v.principal)]]};}
    case "simpleInterest": {const i=v.principal*v.rate/100*v.years;return {primary:usd(v.principal+i),label:"Total value",rows:[["Interest earned",usd(i)],["Starting amount",usd(v.principal)]]};}
    case "compoundInterest": {const total=v.principal*Math.pow(1+v.rate/100,v.years);return {primary:usd(total),label:"Estimated total value",rows:[["Interest earned",usd(total-v.principal)],["Years",f(v.years)]]};}
    case "annualIncome": {const annual=v.hourlyRate*v.hoursPerWeek*v.weeksPerYear;return {primary:usd(annual),label:"Estimated annual income",rows:[["Monthly",usd(annual/12)],["Weekly",usd(v.hourlyRate*v.hoursPerWeek)],["Hourly",usd(v.hourlyRate)]]};}
    case "salesTax": {const tax=v.price*v.taxRate/100;return {primary:usd(v.price+tax),label:"Price including tax",rows:[["Sales tax",usd(tax)],["Before tax",usd(v.price)]]};}
    case "savingsGoal": {const remaining=v.goal-v.saved;return {primary:usd(remaining/v.months),label:"Amount to save each month",rows:[["Remaining",usd(remaining)],["Savings goal",usd(v.goal)]]};}
    case "debtIncome": return {primary:f(v.debt/v.income*100)+"%",label:"Debt-to-income ratio",rows:[["Monthly debt",usd(v.debt)],["Gross monthly income",usd(v.income)]]};
    case "percentOf": return {primary:f(v.part/v.whole*100)+"%",label:"Percentage",rows:[["Part",f(v.part)],["Whole",f(v.whole)]]};
    case "xPercent": return {primary:f(v.percent/100*v.number),label:"Answer",rows:[["Percentage",f(v.percent)+"%"],["Number",f(v.number)]]};
    case "percentChange": return {primary:f((v.end-v.start)/v.start*100)+"%",label:"Percentage change",rows:[["Difference",f(v.end-v.start)],["New value",f(v.end)]]};
    case "percentDifference": return {primary:f(Math.abs(v.first-v.second)/((v.first+v.second)/2)*100)+"%",label:"Percentage difference",rows:[["Difference",f(Math.abs(v.first-v.second))],["Average",f((v.first+v.second)/2)]]};
    case "testGrade": {const score=(v.total-v.wrong)/v.total*100;const grade=score>=97?"A+":score>=93?"A":score>=90?"A-":score>=87?"B+":score>=83?"B":score>=80?"B-":score>=77?"C+":score>=73?"C":score>=70?"C-":score>=67?"D+":score>=63?"D":"F";return {primary:f(score)+"%",label:"Test score",rows:[["Letter grade",grade],["Correct answers",f(v.total-v.wrong)],["Incorrect answers",f(v.wrong)]]};}
    case "reversePercent": return {primary:f(v.final/(v.percent/100)),label:"Original value",rows:[["Final value",f(v.final)],["Percentage remaining",f(v.percent)+"%"]]};
    case "birthYear": {const year=v.year-v.age;return {primary:f(year),label:"Estimated birth year",rows:[["Current age",f(v.age)+" years"],["Current year",f(v.year)],["Range",`${f(year-1)}–${f(year)}`]]};}
    case "ftCm": return {primary:f(v.value*30.48)+" cm",label:"Centimeters",rows:[["Feet",f(v.value)]]}; case "cmFt": return {primary:f(v.value/30.48)+" ft",label:"Feet",rows:[["Centimeters",f(v.value)]]}; case "inCm": return {primary:f(v.value*2.54)+" cm",label:"Centimeters",rows:[["Inches",f(v.value)]]}; case "lbKg": return {primary:f(v.value*0.453592)+" kg",label:"Kilograms",rows:[["Pounds",f(v.value)]]}; case "kgLb": return {primary:f(v.value*2.20462)+" lb",label:"Pounds",rows:[["Kilograms",f(v.value)]]}; case "miKm": return {primary:f(v.value*1.60934)+" km",label:"Kilometers",rows:[["Miles",f(v.value)]]}; case "fC": return {primary:f((v.value-32)*5/9)+" °C",label:"Celsius",rows:[["Fahrenheit",f(v.value)]]}; case "cF": return {primary:f(v.value*9/5+32)+" °F",label:"Fahrenheit",rows:[["Celsius",f(v.value)]]};
    case "bmi": {const bmi=v.weight/Math.pow(v.height/100,2);return {primary:f(bmi),label:"Body mass index",rows:[["Category",bmi<18.5?"Underweight":bmi<25?"Typical range":bmi<30?"Overweight":"Higher range"],["Weight",f(v.weight)+" kg"]]};}
    case "calories": {const bmr=10*v.weight+6.25*v.height-5*v.age-161;return {primary:f(bmr*v.activity)+" kcal",label:"Estimated daily calories",rows:[["Baseline estimate",f(bmr)+" kcal"],["Activity multiplier",f(v.activity)]]};}
    case "pace": return {primary:f(v.minutes/v.distance)+" min/km",label:"Average pace",rows:[["Distance",f(v.distance)+" km"],["Time",f(v.minutes)+" min"]]};
    case "water": {const liters=v.weight*0.033+v.activity*0.012;return {primary:f(liters)+" L",label:"Estimated daily water target",rows:[["Milliliters",f(liters*1000)+" ml"],["Weight",f(v.weight)+" kg"]]};}
    case "average": return {primary:f((v.first+v.second+v.third)/3),label:"Average",rows:[["Sum",f(v.first+v.second+v.third)],["Values","3"]]};
    case "fraction": return {primary:f(v.numerator/v.denominator),label:"Decimal value",rows:[["Fraction",`${f(v.numerator)}/${f(v.denominator)}`],["Percentage",f(v.numerator/v.denominator*100)+"%"]]};
    case "stdDev": {const mean=(v.first+v.second+v.third)/3,sd=Math.sqrt(((v.first-mean)**2+(v.second-mean)**2+(v.third-mean)**2)/3);return {primary:f(sd),label:"Population standard deviation",rows:[["Mean",f(mean)],["Values","3"]]};}
    case "decimalTime": {const hours=Math.floor(v.hours), minutes=Math.round((v.hours-hours)*60);return {primary:`${hours}h ${minutes}m`,label:"Hours and minutes",rows:[["Total minutes",f(v.hours*60)+" min"],["Decimal hours",f(v.hours)]]};}
    case "businessBreakEven": {const contribution=v.price-v.variable, sales=v.fixed/contribution;return {primary:f(sales)+" sales",label:"Break-even sales",rows:[["Contribution per sale",usd(contribution)],["Break-even revenue",usd(sales*v.price)]]};}
    case "roi": return {primary:f((v.gain-v.cost)/v.cost*100)+"%",label:"Return on investment",rows:[["Net return",usd(v.gain-v.cost)],["Investment cost",usd(v.cost)]]};
    case "ratio": {const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;const g=gcd(Math.round(v.first),Math.round(v.second));return {primary:`${v.first/g}:${v.second/g}`,label:"Simplified ratio",rows:[["First",f(v.first)],["Second",f(v.second)]]};}
    case "exponent": return {primary:f(Math.pow(v.base,v.exponent)),label:"Result",rows:[["Expression",`${f(v.base)}^${f(v.exponent)}`]]}; case "sqrt": return {primary:v.value<0?"—":f(Math.sqrt(v.value)),label:"Square root",rows:[["Number",f(v.value)]]};
    case "aiApi": {const one=(v.input/1e6*defaultAIModel.inputPerMillionTokens)+(v.output/1e6*defaultAIModel.outputPerMillionTokens), monthly=one*v.requests*v.days;return {primary:usd(monthly),label:"Estimated monthly API cost",rows:[["Per request",usd(one)],["Daily",usd(one*v.requests)],["Yearly",usd(monthly*12)],["Input cost",usd(v.input/1e6*defaultAIModel.inputPerMillionTokens)],["Output cost",usd(v.output/1e6*defaultAIModel.outputPerMillionTokens)]]};}
    case "aiTokens": {const input=v.input/1e6*defaultAIModel.inputPerMillionTokens,output=v.output/1e6*defaultAIModel.outputPerMillionTokens;return {primary:usd(input+output),label:"Estimated request cost",rows:[["Input",usd(input)],["Output",usd(output)]]};}
    case "tokenEstimate": {const tokens=v.words*1.33;return {primary:f(tokens*v.requests)+" tokens",label:"Estimated total tokens",rows:[["Per request",f(tokens)+" tokens"],["Words",f(v.words)]]};}
    case "chatbot": {const per=(v.input/1e6*defaultAIModel.inputPerMillionTokens)+(v.output/1e6*defaultAIModel.outputPerMillionTokens);return {primary:usd(per*v.conversations),label:"Estimated monthly chatbot cost",rows:[["Per conversation",usd(per)],["Conversations",f(v.conversations)]]};}
    case "saas": {const ai=v.users*v.requests*v.tokens/1e6*defaultAIModel.inputPerMillionTokens, revenue=v.users*v.price,total=ai+v.other,profit=revenue-total;return {primary:usd(profit),label:"Estimated monthly gross profit",rows:[["AI cost",usd(ai)],["Total cost",usd(total)],["Revenue",usd(revenue)],["Gross margin",f(profit/revenue*100)+"%"]]};}
    case "breakEven": {const profit=v.revenue-v.aiCost-v.variable,customers=v.fixed/profit;return {primary:f(customers)+" customers",label:"Break-even customers",rows:[["Profit per customer",usd(profit)],["Break-even revenue",usd(customers*v.revenue)]]};}
    case "generation": {const daily=v.generations*v.cost,monthly=daily*v.days;return {primary:usd(monthly),label:"Estimated monthly cost",rows:[["Daily",usd(daily)],["Annual",usd(monthly*12)]]};}
    default: return {primary:"—",label:"Result",rows:[]};
  }
}
export default function CalculatorClient({ calculator }: { calculator: Calculator }) { const initial=Object.fromEntries(calculator.fields.map(x=>[x.id,x.defaultValue])); const [values,setValues]=useState<Record<string,number>>(initial); const result=useMemo(()=>calculate(calculator,values),[calculator,values]); return <section className="calculator" aria-label={`${calculator.title} form`}><div className="fields">{calculator.fields.map(field=><label key={field.id}>{field.label}<div className="input-wrap">{field.suffix==="$"&&<span>$</span>}<input type="number" min={field.min} value={Number.isFinite(values[field.id])?values[field.id]:""} onChange={e=>setValues(v=>({...v,[field.id]:Number(e.target.value)}))}/>{field.suffix&&field.suffix!=="$"&&<span>{field.suffix}</span>}</div></label>)}</div><div className="result" aria-live="polite"><p>{result.label}</p><strong>{result.primary}</strong><dl>{result.rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button type="button" onClick={()=>setValues(initial)}>Reset values</button></div>{calculator.ai&&<p className="pricing-note">Example pricing data last updated {defaultAIModel.lastUpdated}. AI model pricing changes over time—check the provider’s official pricing before making purchasing decisions.</p>}</section>; }
