"use client";
import type { DynamicRow, DynamicRowsDefinition } from "@/lib/calculators";
type Props = { definition: DynamicRowsDefinition; rows: DynamicRow[]; onChange: (rows: DynamicRow[]) => void };
const blankRow = (definition: DynamicRowsDefinition): DynamicRow => ({ id: `${definition.id}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, ...Object.fromEntries(definition.fields.map((field) => [field.id, field.defaultValue])) });
export default function DynamicRows({ definition, rows, onChange }: Props) {
  const update = (id: string, key: string, value: string | number) => onChange(rows.map((row) => row.id === id ? { ...row, [key]: value } : row));
  const move = (index: number, offset: number) => { const destination = index + offset; if (destination < 0 || destination >= rows.length) return; const next = [...rows]; [next[index], next[destination]] = [next[destination], next[index]]; onChange(next); };
  return <fieldset className="dynamic-rows"><legend>{definition.label}</legend><p className="row-help">Add, edit, reorder, or remove entries. Leave weight at 0 for points-based grading.</p><div className="row-list" aria-live="polite">{rows.map((row, index) => <div className="dynamic-row" key={row.id}>{definition.fields.map((field) => <label key={field.id}>{field.label}<div className="input-wrap"><input type={field.type} min={field.min} value={row[field.id]} onChange={(event) => update(row.id, field.id, field.type === "number" ? Number(event.target.value) : event.target.value)} />{field.suffix && <span>{field.suffix}</span>}</div></label>)}<div className="row-actions"><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label={`Move ${String(row.name || "row")} up`}>↑</button><button type="button" onClick={() => move(index, 1)} disabled={index === rows.length - 1} aria-label={`Move ${String(row.name || "row")} down`}>↓</button><button type="button" onClick={() => onChange(rows.filter((item) => item.id !== row.id))} disabled={rows.length <= (definition.minRows ?? 0)} aria-label={`Remove ${String(row.name || "row")}`}>Remove</button></div></div>)}</div><div className="dynamic-row-footer"><button type="button" className="add-row" onClick={() => onChange([...rows, blankRow(definition)])}>+ {definition.addLabel}</button><button type="button" className="text-button" onClick={() => onChange([])} disabled={rows.length === 0}>Clear rows</button></div></fieldset>;
}
