import { notFound } from "next/navigation";
import type { Metadata } from "next";
import CalculatorClient from "@/components/CalculatorClient";
import GradeCalculator from "@/components/GradeCalculator";
import MaterialCalculatorPage from "@/components/MaterialCalculatorPage";
import {
    calculators, calculatorBySlug, categories,
    type Calculator
} from "@/lib/calculators";
import { Breadcrumbs, Related } from "@/components/Content";

export function generateStaticParams() { return calculators.filter(c => !c.ai).map(c => ({ slug: c.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const c = calculatorBySlug((await params).slug); if (!c) return {}; return c.slug === "grade-calculator" ? { title: "Grade Calculator - Calculate Weighted Course Grades", description: "Calculate weighted course grades, convert letter grades, and plan the score needed on remaining coursework.", alternates: { canonical: "/calculators/grade-calculator" }, openGraph: { title: "Grade Calculator - Calculate Weighted Course Grades", description: "Calculate weighted course grades and plan your final grade." } } : { title: c.title, description: c.description, alternates: { canonical: `/calculators/${c.slug}` } }; }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const c = calculatorBySlug((await params).slug); if (!c || c.ai) notFound(); if (c.slug === "grade-calculator") return <GradePage calculator={c} />; if (c.slug === "mulch-calculator" || c.slug === "concrete-calculator") return <MaterialCalculatorPage calculator={c} kind={c.slug === "mulch-calculator" ? "mulch" : "concrete"} />; return <CalculatorArticle calculator={c} />; }
export function CalculatorArticle({ calculator: c }: { calculator: Calculator }) { return <article className="shell page calculator-page"><Breadcrumbs calculator={c} /><p className="kicker">{categories[c.category].accent}</p><h1>{c.title}</h1><p className="lede">{c.description}</p><CalculatorClient calculator={c} /><section className="article-content"><h2>How this calculator works</h2><p>{c.explanation}</p><h2>Example</h2><p>{c.example}</p></section><Related calculator={c} /></article>; }
function GradePage({ calculator }: { calculator: Calculator }) { return <article className="shell page calculator-page"><Breadcrumbs calculator={calculator} /><p className="kicker">Education</p><h1>Grade Calculator</h1><p className="lede">Calculate your course grade from weighted assignments and exams. Enter percentages or letter grades, then plan what you need on remaining coursework.</p><GradeCalculator /><section className="article-content grade-content"><h2>How weighted grades work</h2><p>Your current average is the sum of each grade multiplied by its weight, divided by the completed weight. If only 60% of a course is graded, the calculator distinguishes that average from its contribution to the final course grade.</p><h2>Formula</h2><p><strong>Weighted grade = Σ(grade × weight) ÷ Σ(weight)</strong></p><p><strong>Required remaining grade = (target grade − current contribution) ÷ remaining weight</strong></p><h2>Worked example</h2><p>Homework is 90% at 10%, a project is 85% at 20%, and a midterm is 88% at 30%. Their contribution is 9 + 17 + 26.4 = 52.4 points. With 40% remaining, a 90% goal requires (90 − 52.4) ÷ 0.40 = 94%.</p><h2>Understanding grading systems</h2><p>Percentage grades measure points earned. Letter grades summarize percentage bands and GPA values, but schools may use different boundaries. This calculator converts letter grades using a standard A+ through F scale.</p><h2>Frequently asked questions</h2><h3>How do I calculate my weighted grade?</h3><p>Multiply each grade by its weight, add the contributions, then divide by the total completed weight.</p><h3>Can I enter letter grades?</h3><p>Yes. Enter grades such as A, B+, or C-. They are converted with the standard grading scale.</p><h3>What if weights do not add to 100%?</h3><p>Missing weight can represent work still to come, so completed work is not divided by 100%.</p><h3>Can I use this for college grades?</h3><p>Yes for weighted courses, but confirm your institution&apos;s grading boundaries and policies.</p><h2>Embed this calculator</h2><pre className="embed-code">{`<iframe src="https://numerocalculators.com/embed/grade-calculator" width="100%" height="700" style="border:0" loading="lazy" title="Grade Calculator"></iframe>`}</pre></section><Related calculator={calculator} /></article>; }
